name = "movie-bite-worker"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "MOVIE_ROOM", class_name = "RoomDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[vars]
TMDB_API_KEY = "15d2ea6d0dc1d476efbca3eba2b9bbfb"
